@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "Anderson Francisco",
	"email": "andersonfranciscoigf@gmail.com",
	"password": "testesenha"
}

###

# @name create_authenticate
POST {{baseUrl}}/session
Content-Type: application/json

{
	"email": "andersonfranciscoigf@gmail.com",
	"password": "testesenha"
}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
